// prisma/seed.ts
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // 保险起见，先把依赖 VipGuest 的东西清空（如果有的话）
  await prisma.message.deleteMany();
  await prisma.session.deleteMany();
  await prisma.pendingApproval.deleteMany();

  // 再清 VipGuest（其实 migrate reset 后是空表，这里多一层保险）
  await prisma.vipGuest.deleteMany();

  await prisma.vipGuest.createMany({
    data: [
      {
        vipNumber: "10001",
        fullName: "Li Wei",
        firstName: "Wei",
        lastName: "Li",
        preferredName: "Mr. Li",
        birthdayMd: "0323",
        preference: "高楼层, 安静房, 非吸烟, 近电梯",
        restriction: "不吃牛肉, 不含酒精",
        contactPhone: "+853 8888 0001",
        contactEmail: "li.wei@example.com",
        profilePhotoUrl: null,
        tier: "Diamond",
        room: "3208",
        checkInDate: new Date("2026-01-10T14:00:00+08:00"),
        checkOutDate: new Date("2026-01-13T12:00:00+08:00"),
        segment: "Casino",
        statusLabel: "In House",
        // ✅ 专属二维码 token（后面 /vip-entry?vipKey= 直接用这个）
        qrCode: "vip-10001-entry",
      },
      {
        vipNumber: "10002",
        fullName: "Zhang Yue",
        firstName: "Yue",
        lastName: "Zhang",
        preferredName: "Ms. Zhang",
        birthdayMd: "0715",
        preference: "低楼层, 靠电梯, 软枕, 晚间开夜床",
        restriction: "海鲜过敏",
        contactPhone: "+852 6666 0002",
        contactEmail: "zhang.yue@example.com",
        profilePhotoUrl: null,
        tier: "Platinum",
        room: "1605",
        checkInDate: new Date("2026-01-09T17:30:00+08:00"),
        checkOutDate: new Date("2026-01-11T12:00:00+08:00"),
        segment: "Leisure",
        statusLabel: "Checked Out",
        qrCode: "vip-10002-entry",
      },
      {
        vipNumber: "10003",
        fullName: "Chan Ka Ho",
        firstName: "Ka Ho",
        lastName: "Chan",
        preferredName: "Mr. Chan",
        birthdayMd: "1118",
        preference: "靠电梯, 靠景观窗, 非吸烟, 晚班清洁",
        restriction: "",
        contactPhone: "+853 9888 0003",
        contactEmail: "kaho.chan@example.com",
        profilePhotoUrl: null,
        tier: "Diamond",
        room: "2801",
        checkInDate: new Date("2026-01-11T15:00:00+08:00"),
        checkOutDate: new Date("2026-01-15T12:00:00+08:00"),
        segment: "Business",
        statusLabel: "Arriving",
        qrCode: "vip-10003-entry",
      },
      {
        vipNumber: "10004",
        fullName: "Wong Mei Ling",
        firstName: "Mei Ling",
        lastName: "Wong",
        preferredName: "Ms. Wong",
        birthdayMd: "0229",
        preference: "高楼层, 靠电梯, 软床垫, 纯素餐饮",
        restriction: "不吃鸡蛋, 不吃奶制品",
        contactPhone: "+86 139 0000 0004",
        contactEmail: "ml.wong@example.com",
        profilePhotoUrl: null,
        tier: "Elite",
        room: null,
        checkInDate: null,
        checkOutDate: null,
        segment: "Leisure",
        statusLabel: "Profile Only",
        qrCode: "vip-10004-entry",
      },
      {
        vipNumber: "10005",
        fullName: "Lin Hao",
        firstName: "Hao",
        lastName: "Lin",
        preferredName: "Hao",
        birthdayMd: "1203",
        preference: "安静房, 远离电梯, 硬枕, 早班清洁",
        restriction: "",
        contactPhone: "+86 137 0000 0005",
        contactEmail: "hao.lin@example.com",
        profilePhotoUrl: null,
        tier: "Gold",
        room: "1012",
        checkInDate: new Date("2025-12-20T16:00:00+08:00"),
        checkOutDate: new Date("2025-12-23T12:00:00+08:00"),
        segment: "Casino",
        statusLabel: "History",
        qrCode: "vip-10005-entry",
      },
      {
        vipNumber: "10009",
        fullName: "Tang Yi",
        firstName: "Yi",
        lastName: "Tang",
        preferredName: "Mr. Tang",
        birthdayMd: "0501",
        preference: "湖景房, 高楼层, 非吸烟, 晚退房",
        restriction: "不含坚果",
        contactPhone: "+853 9888 0009",
        contactEmail: "tang.yi@example.com",
        profilePhotoUrl: null,
        tier: "Diamond",
        room: "3506",
        checkInDate: new Date("2026-01-10T18:00:00+08:00"),
        checkOutDate: new Date("2026-01-14T12:00:00+08:00"),
        segment: "Casino",
        statusLabel: "In House",
        qrCode: "vip-10009-entry",
      },
      {
        vipNumber: "20001",
        fullName: "Kim Min Jun",
        firstName: "Min Jun",
        lastName: "Kim",
        preferredName: "Mr. Kim",
        birthdayMd: "0812",
        preference: "高楼层, 近电梯, 韩式早餐, 英文服务",
        restriction: "",
        contactPhone: "+82 10-0000-0001",
        contactEmail: "minjun.kim@example.com",
        profilePhotoUrl: null,
        tier: "Platinum",
        room: "2703",
        checkInDate: new Date("2026-01-11T13:30:00+08:00"),
        checkOutDate: new Date("2026-01-12T12:00:00+08:00"),
        segment: "Leisure",
        statusLabel: "In House",
        qrCode: "vip-20001-entry",
      },
      {
        vipNumber: "20002",
        fullName: "Sato Haruka",
        firstName: "Haruka",
        lastName: "Sato",
        preferredName: "Ms. Sato",
        birthdayMd: "0310",
        preference: "日文服务, 靠电梯, 靠景观窗, 和式早餐",
        restriction: "不吃生鱼",
        contactPhone: "+81 90-0000-0002",
        contactEmail: "haruka.sato@example.com",
        profilePhotoUrl: null,
        tier: "Gold",
        room: null,
        checkInDate: null,
        checkOutDate: null,
        segment: "Leisure",
        statusLabel: "Profile Only",
        qrCode: "vip-20002-entry",
      },
      {
        vipNumber: "20003",
        fullName: "Chen Rong",
        firstName: "Rong",
        lastName: "Chen",
        preferredName: "Mr. Chen",
        birthdayMd: "0919",
        preference: "靠电梯, 非吸烟, 枕头菜单, 夜宵服务",
        restriction: "",
        contactPhone: "+86 138 0000 0003",
        contactEmail: "rong.chen@example.com",
        profilePhotoUrl: null,
        tier: "Elite",
        room: "1909",
        checkInDate: new Date("2025-12-15T15:00:00+08:00"),
        checkOutDate: new Date("2025-12-18T12:00:00+08:00"),
        segment: "Business",
        statusLabel: "History",
        qrCode: "vip-20003-entry",
      },
      {
        vipNumber: "20005",
        fullName: "Ng Pui Yan",
        firstName: "Pui Yan",
        lastName: "Ng",
        preferredName: "Pui Yan",
        birthdayMd: null,
        preference: "高楼层, 湖景房, 纯素选项, 下午茶",
        restriction: "",
        contactPhone: "+853 6888 0005",
        contactEmail: "puiyan.ng@example.com",
        profilePhotoUrl: null,
        tier: "Diamond",
        room: "3302",
        checkInDate: new Date("2026-01-09T14:00:00+08:00"),
        checkOutDate: new Date("2026-01-12T12:00:00+08:00"),
        segment: "Casino",
        statusLabel: "In House",
        qrCode: "vip-20005-entry",
      },
    ],
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
