import { Conversation, Message, GuestProfile } from '@/types';

export const mockConversations: Conversation[] = [
  {
    id: '1',
    channel: 'wechat',
    displayName: 'Jayvion Simon',
    lastMessagePreview: 'You: How To Boost...',
    lastMessageAtLabel: '3 days',
    unreadCount: 1,
    vip: true,
    online: true,
    room: '304',
    vipTier: 'Diamond',
  },
  {
    id: '2',
    channel: 'whatsapp',
    displayName: 'Reece Chung',
    lastMessagePreview: '6 Powerful Tips To...',
    lastMessageAtLabel: '10 hours',
    unreadCount: 0,
    vip: false,
    online: false,
    room: '512',
    vipTier: 'Gold',
  },
  {
    id: '3',
    channel: 'line',
    displayName: 'Lucian Obrien',
    lastMessagePreview: 'How To Boost Traffic...',
    lastMessageAtLabel: '1 hours',
    unreadCount: 0,
    vip: false,
    online: true,
    room: '210',
    vipTier: 'Platinum',
  },
  {
    id: '4',
    channel: 'webchat',
    displayName: 'Deja Brady',
    lastMessagePreview: 'Internet Banner...',
    lastMessageAtLabel: '10 hours',
    unreadCount: 0,
    vip: false,
    online: false,
    room: '405',
    vipTier: 'Red',
  },
  {
    id: '5',
    channel: 'email',
    displayName: 'Harrison Stein',
    lastMessagePreview: 'Free Real Estate...',
    lastMessageAtLabel: '3 days',
    unreadCount: 1,
    vip: false,
    online: false,
    room: '128',
    vipTier: 'Black',
  },
  {
    id: '6',
    channel: 'phone',
    displayName: 'Cristopher Cardenas',
    lastMessagePreview: 'Advertisers Embrace...',
    lastMessageAtLabel: '10 hours',
    unreadCount: 0,
    vip: true,
    online: true,
    room: '901',
    vipTier: 'Chairman',
  },
  {
    id: '7',
    channel: 'wechat',
    displayName: 'Melanie Noble',
    lastMessagePreview: 'Nine Features Of An...',
    lastMessageAtLabel: '10 hours',
    unreadCount: 0,
    vip: false,
    online: true,
    room: '322',
    vipTier: 'Platinum',
  },
  {
    id: '8',
    channel: 'whatsapp',
    displayName: 'Shawn Manning',
    lastMessagePreview: '7 Ways To Advertise...',
    lastMessageAtLabel: '10 hours',
    unreadCount: 0,
    vip: false,
    online: false,
    room: '618',
    vipTier: 'Gold',
  },
  {
    id: '9',
    channel: 'line',
    displayName: 'Soren Durham',
    lastMessagePreview: 'Influencing The...',
    lastMessageAtLabel: '10 hours',
    unreadCount: 0,
    vip: false,
    online: true,
    room: '735',
    vipTier: 'Diamond',
  },
];

export const mockMessages: Record<string, Message[]> = {
  '1': [
    {
      id: 'm1',
      conversationId: '1',
      direction: 'in',
      text: 'Hey John, I am looking for the best admin template. Could you please help me to find it out?😃',
      timeLabel: '4:02 PM',
      dateLabel: '21 Jan 2021',
      timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    },
    {
      id: 'm2',
      conversationId: '1',
      direction: 'out',
      text: 'Stack admin is the responsive bootstrap 4 admin template.',
      timeLabel: '4:02 PM',
      timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000 + 60000,
    },
    {
      id: 'm3',
      conversationId: '1',
      direction: 'in',
      text: 'Looks clean and fresh UI.😃',
      timeLabel: '4:02 PM',
      timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000 + 120000,
    },
  ],
  '2': [
    {
      id: 'm4',
      conversationId: '2',
      direction: 'in',
      text: 'Hello! I need some help with my room reservation.',
      timeLabel: '9:15 AM',
      dateLabel: '20 Jan 2021',
      timestamp: Date.now() - 10 * 60 * 60 * 1000,
    },
    {
      id: 'm5',
      conversationId: '2',
      direction: 'out',
      text: 'Of course! I would be happy to assist you. What do you need help with?',
      timeLabel: '9:16 AM',
      timestamp: Date.now() - 10 * 60 * 60 * 1000 + 60000,
    },
    {
      id: 'm6',
      conversationId: '2',
      direction: 'in',
      text: 'I would like to extend my stay for two more nights.',
      timeLabel: '9:18 AM',
      timestamp: Date.now() - 10 * 60 * 60 * 1000 + 180000,
    },
  ],
  '3': [
    {
      id: 'm7',
      conversationId: '3',
      direction: 'in',
      text: 'Good morning! Can I get extra towels in my room?',
      timeLabel: '8:30 AM',
      dateLabel: '20 Jan 2021',
      timestamp: Date.now() - 1 * 60 * 60 * 1000,
    },
    {
      id: 'm8',
      conversationId: '3',
      direction: 'out',
      text: 'Good morning! Absolutely, I will send housekeeping to your room right away.',
      timeLabel: '8:32 AM',
      timestamp: Date.now() - 1 * 60 * 60 * 1000 + 120000,
    },
  ],
  '4': [
    {
      id: 'm9',
      conversationId: '4',
      direction: 'in',
      text: 'Hi there! What time is breakfast served?',
      timeLabel: '7:45 AM',
      dateLabel: '19 Jan 2021',
      timestamp: Date.now() - 10 * 60 * 60 * 1000,
    },
    {
      id: 'm10',
      conversationId: '4',
      direction: 'out',
      text: 'Hello! Breakfast is served from 6:30 AM to 10:30 AM in our main dining room.',
      timeLabel: '7:46 AM',
      timestamp: Date.now() - 10 * 60 * 60 * 1000 + 60000,
    },
  ],
  '5': [
    {
      id: 'm11',
      conversationId: '5',
      direction: 'in',
      text: 'I have a question about the spa services. Are they available today?',
      timeLabel: '2:20 PM',
      dateLabel: '18 Jan 2021',
      timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000,
    },
    {
      id: 'm12',
      conversationId: '5',
      direction: 'out',
      text: 'Yes, our spa is open from 9 AM to 8 PM. Would you like me to book a treatment for you?',
      timeLabel: '2:22 PM',
      timestamp: Date.now() - 3 * 24 * 60 * 60 * 1000 + 120000,
    },
  ],
  '6': [
    {
      id: 'm13',
      conversationId: '6',
      direction: 'in',
      text: 'Could you recommend a good restaurant nearby?',
      timeLabel: '6:10 PM',
      dateLabel: '18 Jan 2021',
      timestamp: Date.now() - 10 * 60 * 60 * 1000,
    },
    {
      id: 'm14',
      conversationId: '6',
      direction: 'out',
      text: 'Certainly! We have an excellent Italian restaurant just 5 minutes away. I can make a reservation for you.',
      timeLabel: '6:12 PM',
      timestamp: Date.now() - 10 * 60 * 60 * 1000 + 120000,
    },
  ],
  '7': [
    {
      id: 'm15',
      conversationId: '7',
      direction: 'in',
      text: 'The Wi-Fi password is not working in my room.',
      timeLabel: '11:30 AM',
      dateLabel: '17 Jan 2021',
      timestamp: Date.now() - 10 * 60 * 60 * 1000,
    },
    {
      id: 'm16',
      conversationId: '7',
      direction: 'out',
      text: 'I apologize for the inconvenience. The current password is: HotelGuest2021. Please try that.',
      timeLabel: '11:32 AM',
      timestamp: Date.now() - 10 * 60 * 60 * 1000 + 120000,
    },
  ],
  '8': [
    {
      id: 'm17',
      conversationId: '8',
      direction: 'in',
      text: 'Can I get a late checkout tomorrow?',
      timeLabel: '5:45 PM',
      dateLabel: '17 Jan 2021',
      timestamp: Date.now() - 10 * 60 * 60 * 1000,
    },
    {
      id: 'm18',
      conversationId: '8',
      direction: 'out',
      text: 'Let me check availability for you. Yes, we can accommodate a late checkout until 2 PM.',
      timeLabel: '5:47 PM',
      timestamp: Date.now() - 10 * 60 * 60 * 1000 + 120000,
    },
  ],
  '9': [
    {
      id: 'm19',
      conversationId: '9',
      direction: 'in',
      text: 'Is there a gym in the hotel?',
      timeLabel: '7:00 AM',
      dateLabel: '16 Jan 2021',
      timestamp: Date.now() - 10 * 60 * 60 * 1000,
    },
    {
      id: 'm20',
      conversationId: '9',
      direction: 'out',
      text: 'Yes! Our fitness center is on the 3rd floor and is open 24/7 for all guests.',
      timeLabel: '7:02 AM',
      timestamp: Date.now() - 10 * 60 * 60 * 1000 + 120000,
    },
  ],
};

export const mockProfiles: Record<string, GuestProfile> = {
  '1': {
    conversationId: '1',
    name: 'Jayvion Simon',
    room: '304',
    checkInDate: '21 Jan 2021',
    checkOutDate: '23 Jan 2021',
    segment: 'Business',
    statusLabel: 'Check in',
    vipTier: 'Diamond',
    preferredName: 'Jay',
    vipNumber: 'VIP-D-10234',
    notes: 'Drinks coffee every morning at 7 AM. Prefers non-smoking rooms. Enjoys Cuban cigars - favorite brand is Cohiba.',
  },
  '2': {
    conversationId: '2',
    name: 'Reece Chung',
    room: '512',
    checkInDate: '19 Jan 2021',
    checkOutDate: '25 Jan 2021',
    segment: 'Leisure',
    statusLabel: 'Check in',
    vipTier: 'Gold',
    preferredName: 'Reece',
    vipNumber: 'VIP-G-45821',
    notes: 'Allergic to feather pillows. Prefers high floor with city view.',
  },
  '3': {
    conversationId: '3',
    name: 'Lucian Obrien',
    room: '210',
    checkInDate: '20 Jan 2021',
    checkOutDate: '22 Jan 2021',
    segment: 'Business',
    statusLabel: 'Check in',
    vipTier: 'Platinum',
    preferredName: 'Lucian',
    vipNumber: 'VIP-P-29384',
    notes: 'Frequent business traveler. Prefers early check-in when available.',
  },
  '4': {
    conversationId: '4',
    name: 'Deja Brady',
    room: '405',
    checkInDate: '18 Jan 2021',
    checkOutDate: '21 Jan 2021',
    segment: 'Leisure',
    statusLabel: 'Check in',
    vipTier: 'Red',
    preferredName: 'Deja',
    vipNumber: 'VIP-R-77492',
    notes: 'Traveling with family. Requested extra towels and toiletries.',
  },
  '5': {
    conversationId: '5',
    name: 'Harrison Stein',
    room: '128',
    checkInDate: '17 Jan 2021',
    checkOutDate: '20 Jan 2021',
    segment: 'Business',
    statusLabel: 'Check in',
    vipTier: 'Black',
    preferredName: 'Harry',
    vipNumber: 'VIP-B-19283',
    notes: 'Regular spa guest. Prefers Swedish massage. Enjoys afternoon tea service.',
  },
  '6': {
    conversationId: '6',
    name: 'Cristopher Cardenas',
    room: '901',
    checkInDate: '18 Jan 2021',
    checkOutDate: '24 Jan 2021',
    segment: 'Leisure',
    statusLabel: 'Check in',
    vipTier: 'Chairman',
    preferredName: 'Chris',
    vipNumber: 'VIP-C-00123',
    notes: 'VIP Chairman tier. Prefers suite with private butler service. Enjoys fine dining and wine tasting.',
  },
  '7': {
    conversationId: '7',
    name: 'Melanie Noble',
    room: '322',
    checkInDate: '19 Jan 2021',
    checkOutDate: '23 Jan 2021',
    segment: 'Business',
    statusLabel: 'Check in',
    vipTier: 'Platinum',
    preferredName: 'Mel',
    vipNumber: 'VIP-P-55091',
    notes: 'Prefers quiet rooms away from elevators. Enjoys room service breakfast.',
  },
  '8': {
    conversationId: '8',
    name: 'Shawn Manning',
    room: '618',
    checkInDate: '17 Jan 2021',
    checkOutDate: '21 Jan 2021',
    segment: 'Leisure',
    statusLabel: 'Check in',
    vipTier: 'Gold',
    preferredName: 'Shawn',
    vipNumber: 'VIP-G-33187',
    notes: 'Gym enthusiast. Requests wake-up calls at 6 AM. Enjoys protein-rich breakfast.',
  },
  '9': {
    conversationId: '9',
    name: 'Soren Durham',
    room: '735',
    checkInDate: '16 Jan 2021',
    checkOutDate: '19 Jan 2021',
    segment: 'Business',
    statusLabel: 'Check in',
    vipTier: 'Diamond',
    preferredName: 'Soren',
    vipNumber: 'VIP-D-88204',
    notes: 'Tech-savvy guest. Appreciates smart room features. Prefers digital check-in/out.',
  },
};
